### ISSUE TITLE
Fungible token standard

### ISSUE THREAD

**Issue by agraebe** [stacksgov/sips#1]
As per previous discussions ([see Paper doc](https://paper.dropbox.com/doc/Working-group-Stacks-Token-Standard--BCnkvBjpEg~uI25yo8oFT1J2AQ-Hmix9Te1J9x7qYmTvlrqZ)), @psq will create a proposal for a fungible token standard.

I'm creating this to keep track of the conversations

**Comment by friedger** [comment]
Defined and ratified. Can be closed.
