### ISSUE TITLE
Create template for CAB minutes

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/sips#100]
Now that we have more active CABs reviewing SIP-015 it would be good to reduce this work back to a consistent template that all CABs can use.

PRs for SIP-015 minutes:

- #97 
- #98 
- #99 

The formatting is very close across all three, and the Economics CAB included a generic template file in their submission.

Given that we have a `TEMPLATE.MD` for the CAB formation, it'd be great to also create one for meeting minutes using that as a starting point.

Some things that come to mind for me, and open to feedback on what works best for the CABs.

- ISO-8601 dates and informative file names, e.g. `2022-10-31-sip-015.md`
- UTC for meeting times, e.g. `15:00 - 16:00 UTC`
- consistent sections and fields, e.g. Meeting Information

We can revisit this after all the PRs are merged in, and ideally set something up for the next SIP so it's even easier!

**Comment by Hero-Gamer** [comment]
100% need! Thank you so much Jason! <3
