### ISSUE TITLE
Non-fungible token standard

### ISSUE THREAD

**Issue by agraebe** [stacksgov/sips#2]
As per previous discussions ([see Paper doc](https://paper.dropbox.com/doc/Working-group-Stacks-Token-Standard--BCnkvBjpEg~uI25yo8oFT1J2AQ-Hmix9Te1J9x7qYmTvlrqZ)), @friedger will create a proposal for a non-fungible token standard.

I'm creating this to keep track of the conversations

**Comment by agraebe** [comment]
the most recent NFT proposal is in here: https://github.com/friedger/sips/blob/main/nft-standard.md

@markmhx and @hstove could you take a look please?

**Comment by hstove** [comment]
@friedger please open a PR so we can properly review, etc!

**Comment by friedger** [comment]
There are now more than 5 contracts on mainnet that implement the trait. See also https://tofauti.net
