### ISSUE TITLE
Diversity - Consideration Advisory Board

### ISSUE THREAD

**Issue by Hero-Gamer** [stacksgov/sips#64]
Hi all, appreciate for opening such consideration panel for the wider community to participate. 
Just would like to express my interest in this particular CAB. 

Let me know if it is possible :)
Thanks. CC: @jcnelson

**Comment by jcnelson** [comment]
Hey @Hero-Gamer, all you have to do is submit a PR to this repo that adds yourself as a member of this CAB (in `considerations/diversity.md`).

**Comment by Hero-Gamer** [comment]
Hi @jcnelson , I couldn't quite find the right route to editing the doc via the Pull Request tab, so I asked around and did it via the **Code** tab going into the folder and edit file **[diversity.md]** which then says **Propose Changes** which generated a Repository in my profile or something. Not sure if I had done it right. I hope so!  (sorry still completely unfamiliar with GH)

**Comment by jcnelson** [comment]
Added. Welcome aboard :)
